services:
  reverse_proxy:
    image: nginx:1.27-bookworm
    container_name: reverse_proxy_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    name: reverse_proxy
    driver: bridge
